### ISSUE TITLE
Internal updater does not remove previous version

### ISSUE THREAD

**Issue by BurninTurtles** [Bluegrams/PinWin#4]
I ran the update today from within PinWin and it umpromptedly rebooted my machine. okay, whatever. But once the machine rebooted and I logged in, I had received the same error that one would see when trying to launch a second instance of PinWin. upon further inspection, both 0.2.2 and 0.2.1 are still installed, both are set to start up at login, both are visible/removable from ControlPanel\AddRemovePrograms, and there are 2 seperate install Dirs in C:\Windows\Installer\{UUID? of program version}

**Comment by alxnull** [comment]
I tried to reproduce this but the update to v.0.2.2 works without problems on my PC, with the previous version being removed and only entries for the current version left. Maybe the installation was unfinished when the reboot happened. At the moment, I also don't really know if and how the reboot could be caused by the update.
Does this happen again if you re-install the previous version and run the update once more?

**Comment by BurninTurtles** [comment]
I followed the above advice by removing PinWin, rebooting for good measure, installing v0.2.1 and then following the prompt to update to v0.2.2. v0.2.1 is still not removed an 2 entries appear in the add/remove programs list. 

EDIT: does the updater generate a log file anywhere on the machine that I could post?

**Comment by alxnull** [comment]
Did a bit of experimenting and found one possible cause for the updater to fail is that it does not force the old executable of PinWin to terminate. I have pushed an [updated setup msi](https://sourceforge.net/projects/pinwin/files/v.0.2.2/PinWinSetup_Updated.msi/download) that's now also used by the internal automatic update. I'd be glad if you could run the procedure you described once again and see if anything has changed.

**Comment by BurninTurtles** [comment]
So I have replicated the steps above and I still see 2 versions of the program in add/remove programs. With that being said, when I remove all versions, reinstall version 0.2.1 then run the updated msi, this works as expected in that the old version is removed, new version is installed, and only that version remains. I also noticed the tweak you mentioned directly above, that pin win is now terminated before the install process happens. I am not sure if this would be at play, but I noticed that PinWin is not restarted after being updated in ideal update conditions (old version removed).

Also this may be worth noting. When I open up version 0.2.1 for the first time, and am immediately greeted with the new update notification, if I click update, I do not see any progress happening. However, if I go to the PinWin 0.2.1 icon in the tray, right click, choose about, then click update from this window, the full interactive windows installer appears. I am able to replicate this on 2 other machines as well.

Thank you for your patience and work thusfar.

**Comment by alxnull** [comment]
> With that being said, when I remove all versions, reinstall version 0.2.1 then run the updated msi, this works as expected in that the old version is removed, new version is installed, and only that version remains.

This sounds good. If two versions of PinWin are already present on the system after running the faulty updater, the best option probably really is to uninstall all versions manually and make a clean reinstall afterwards.

>  I noticed that PinWin is not restarted after being updated in ideal update conditions (old version removed).

This is expected behaviour at the moment. However, automatically restarting the app after updating definitely is a useful addition to be included in the next version.

> When I open up version 0.2.1 for the first time, and am immediately greeted with the new update notification, if I click update, I do not see any progress happening. 

So the update does not start at all if you click the "Update" button? I'll see if I can reproduce this.

Also, thank you very much for helping to fix these issues by doing such detailed testing.

**Comment by BurninTurtles** [comment]
> So the update does not start at all if you click the "Update" button? I'll see if I can reproduce this.

This is correct. when opening PinWin v0.2.1 and clicking Update from the prompt window, the installer does not appear to run. However If I go into about and then click update, it does appear to work. Is it possible that clicking update from the prompt at startup runs the windows installer automatically in the background, whereas the update button from the about screen runs it in an interactive mode? I don't believe this would be the case, as I would still expect to receive a windows UAC dialog.

No, thank you for being receptive. I've seen Devs be much more callous ;)

**Comment by alxnull** [comment]
> Is it possible that clicking update from the prompt at startup runs the windows installer automatically in the background, whereas the update button from the about screen runs it in an interactive mode?

Actually, both routes use the exact same code to run the installer, so I haven't figured out yet where these differences might come from. Unfortunately, I also could not reproduce what you describe up to now.

Meanwhile, I learned a bit more about Windows installers and [built yet another completely new setup package](https://sourceforge.net/projects/pinwin/files/v.0.2.2/PinWinSetup_Updated_v2.msi/download) (that also restarts the app after upgrading). There might be the chance that it turns out to be a bit less buggy than the old one :)
